apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: default
type: Opaque
stringData:
  root-user: minioadmin
  root-password: minioadmin123
  console-password: consolepass123
