version: 2

sources:
  - name: lakekeeper_catalog
    description: "Iceberg catalog managed by Lakekeeper, containing extracted pancake data"
    database: lakekeeper_catalog
    schema: pancake_analytics
    tables:
      - name: pancakes
        description: "Raw pancake records extracted from PostgreSQL database"
        columns:
          - name: id
            description: "Primary key - unique pancake identifier"
            tests:
              - unique
              - not_null
          
          - name: name
            description: "Name of the pancake creation"
            tests:
              - not_null
          
          - name: fluffiness_level
            description: "Fluffiness rating from 1-10"
          
          - name: syrup_type
            description: "Type of syrup (maple, chocolate, strawberry, etc.)"
          
          - name: is_buttery
            description: "Whether the pancake has butter"
          
          - name: magical_factor
            description: "Magical rating (0-10 with decimals)"
          
          - name: created_at
            description: "Timestamp when the pancake was created"
            tests:
              - not_null
          
          - name: taste_notes
            description: "Free-form text notes about the pancake's taste"
