apiVersion: v1
kind: Service
metadata:
  name: pancake-backend
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: pancake-backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
