apiVersion: v1
kind: Service
metadata:
  name: pancake-backend
  namespace: default
spec:
  type: NodePort
  selector:
    app: pancake-backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30090
    protocol: TCP
