duckdb_dbt:

  target: local
  outputs:
    local:
      type: duckdb
      path: dbt.duckdb
      threads: 24
      extensions:
        - iceberg
      database: lakekeeper_catalog
      disable_transactions: true
      attach:
        - path: iceberg-lakehouse-local
          alias: lakekeeper_catalog
          type: iceberg
          options:
            endpoint: 'http://localhost:8181/catalog'
            authorization_type: 'none'
        - path: postgresql://pancake_db_reader_writer:supersecretpasswordoftheages@192.168.64.2:30042/happy_pancakes
          alias: pancakes_postgres
          type: postgres

