apiVersion: v1
kind: Service
metadata:
  annotations:
    cnpg.io/operatorVersion: 1.28.0
  creationTimestamp: "2025-12-14T10:31:03Z"
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: local-postgres
    app.kubernetes.io/managed-by: cloudnative-pg
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: "16"
    cnpg.io/cluster: local-postgres
  name: local-postgres-r
  namespace: default
  ownerReferences:
  - apiVersion: postgresql.cnpg.io/v1
    controller: true
    kind: Cluster
    name: local-postgres
    uid: 2d0d793e-2985-4fa6-b913-d317e60a4585
  resourceVersion: "42870"
  uid: df2c15c1-bcff-47c6-877a-c2e13d27c875
spec:
  clusterIP: 10.43.43.172
  clusterIPs:
  - 10.43.43.172
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 30042
  selector:
    cnpg.io/cluster: local-postgres
    cnpg.io/podRole: instance
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
